services:
  postgres:
    image: postgres:14
    container_name: postgres_raketa
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - raketa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_raketa
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks:
      - raketa_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: redis_raketa
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--dir', '/data']
    networks:
      - raketa_network
    volumes:
      - redisdata:/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - raketa_network
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  raketa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raketa_bot
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - raketa_network
    expose:
      - '80'
    labels:
      - 'traefik.enable=true'
      # Middleware для перенаправления HTTP на HTTPS
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      # Middleware для удаления префиксов
      - 'traefik.http.middlewares.customer-stripprefix.stripprefix.prefixes=/webhook/customer'
      - 'traefik.http.middlewares.courier-stripprefix.stripprefix.prefixes=/webhook/courier'
      - 'traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/webhook/admin'
      - 'traefik.http.middlewares.partner-stripprefix.stripprefix.prefixes=/webhook/partner'
      # Один сервис для контейнера raketa_bot
      - 'traefik.http.services.raketa-service.loadbalancer.server.port=80'
      # Роутер для /webhook/customer
      - 'traefik.http.routers.raketa-customer.rule=Host(`raketago.ru`) && PathPrefix(`/webhook/customer`)'
      - 'traefik.http.routers.raketa-customer.entrypoints=websecure'
      - 'traefik.http.routers.raketa-customer.tls=true'
      - 'traefik.http.routers.raketa-customer.tls.certresolver=le'
      - 'traefik.http.routers.raketa-customer.middlewares=customer-stripprefix'
      - 'traefik.http.routers.raketa-customer.service=raketa-service'
      # Роутер для /webhook/courier
      - 'traefik.http.routers.raketa-courier.rule=Host(`raketago.ru`) && PathPrefix(`/webhook/courier`)'
      - 'traefik.http.routers.raketa-courier.entrypoints=websecure'
      - 'traefik.http.routers.raketa-courier.tls=true'
      - 'traefik.http.routers.raketa-courier.tls.certresolver=le'
      - 'traefik.http.routers.raketa-courier.middlewares=courier-stripprefix'
      - 'traefik.http.routers.raketa-courier.service=raketa-service'
      # Роутер для /webhook/admin
      - 'traefik.http.routers.raketa-admin.rule=Host(`raketago.ru`) && PathPrefix(`/webhook/admin`)'
      - 'traefik.http.routers.raketa-admin.entrypoints=websecure'
      - 'traefik.http.routers.raketa-admin.tls=true'
      - 'traefik.http.routers.raketa-admin.tls.certresolver=le'
      - 'traefik.http.routers.raketa-admin.middlewares=admin-stripprefix'
      - 'traefik.http.routers.raketa-admin.service=raketa-service'
      # Роутер для /webhook/partner
      - 'traefik.http.routers.raketa-partner.rule=Host(`raketago.ru`) && PathPrefix(`/webhook/partner`)'
      - 'traefik.http.routers.raketa-partner.entrypoints=websecure'
      - 'traefik.http.routers.raketa-partner.tls=true'
      - 'traefik.http.routers.raketa-partner.tls.certresolver=le'
      - 'traefik.http.routers.raketa-partner.middlewares=partner-stripprefix'
      - 'traefik.http.routers.raketa-partner.service=raketa-service'

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - '--api.insecure=true' # Для отладки, в продакшене отключите
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=raketa_network' # Явно указываем сеть
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--certificatesresolvers.le.acme.email=${EMAIL}'
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.le.acme.httpchallenge=true'
      - '--certificatesresolvers.le.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'traefik_letsencrypt:/letsencrypt'
    networks:
      - raketa_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./promtail-data:/data
    command: -config.file=/etc/promtail/config.yaml
    privileged: true
    networks:
      - raketa_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - raketa_network

networks:
  raketa_network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  redisdata:
  grafana_data:
  traefik_letsencrypt:
# services:
#   postgres:
#     image: postgres:14
#     container_name: postgres_raketa
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#     ports:
#       - '0.0.0.0:5432:5432'
#     networks:
#       - raketa_network
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq_raketa
#     restart: unless-stopped
#     environment:
#       RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
#       RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
#     ports:
#       - '127.0.0.1:5672:5672'
#       - '127.0.0.1:15672:15672'
#     networks:
#       - raketa_network
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq

#   redis:
#     image: redis:7
#     container_name: redis_raketa
#     restart: unless-stopped
#     ports:
#       - '127.0.0.1:6379:6379'
#     command: ['redis-server', '--dir', '/data']
#     networks:
#       - raketa_network
#     volumes:
#       - redisdata:/data

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     restart: unless-stopped
#     ports:
#       - '3000:3000'
#     environment:
#       - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
#       - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
#       - GF_AUTH_ANONYMOUS_ENABLED=true
#       - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
#     networks:
#       - raketa_network
#     depends_on:
#       - postgres
#     volumes:
#       - grafana_data:/var/lib/grafana

#   raketa:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: raketa_bot
#     restart: unless-stopped
#     env_file:
#       - .env
#       - .env.local
#     depends_on:
#       - postgres
#       - rabbitmq
#       - redis
#     networks:
#       - raketa_network
#     ports:
#       - '127.0.0.1:8000:80'

#   promtail:
#     image: grafana/promtail:latest
#     container_name: promtail
#     restart: unless-stopped
#     ports:
#       - '9080:9080'
#     volumes:
#       - /var/lib/docker/containers:/var/lib/docker/containers:ro
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./promtail-config.yaml:/etc/promtail/config.yaml
#       - ./promtail-data:/data # ← вот эта строка нужна
#     command: -config.file=/etc/promtail/config.yaml
#     privileged: true
#     networks:
#       - raketa_network
#   loki:
#     image: grafana/loki:latest
#     container_name: loki
#     restart: unless-stopped
#     ports:
#       - '3100:3100'
#     volumes:
#       - ./loki-config.yaml:/etc/loki/local-config.yaml
#     command: -config.file=/etc/loki/local-config.yaml
#     networks:
#       - raketa_network

# networks:
#   raketa_network:
#     driver: bridge

# volumes:
#   rabbitmq_data:
#   postgres_data:
#   redisdata:
#   grafana_data:
