services:
  postgres:
    image: postgres:14
    container_name: postgres_raketa
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - raketa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_raketa
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks:
      - raketa_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: redis_raketa
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--dir', '/data']
    networks:
      - raketa_network
    volumes:
      - redisdata:/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - raketa_network
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

  raketa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raketa_bot
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - raketa_network
    ports:
      - '443:80'
    labels:
      - 'traefik.enable=true'

      # Общие настройки middleware
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/webhook/customer,/webhook/courier,/webhook/admin,/webhook/partner'

      # Customer bot
      - 'traefik.http.routers.customer.rule=Host(`customer.raketa.ru`) && PathPrefix(`/webhook/customer`)'
      - 'traefik.http.routers.customer.entrypoints=websecure'
      - 'traefik.http.routers.customer.tls=true'
      - 'traefik.http.routers.customer.tls.certresolver=le'
      - 'traefik.http.routers.customer.middlewares=strip-prefix'
      - 'traefik.http.services.customer.loadbalancer.server.port=80'

      # Courier bot
      - 'traefik.http.routers.courier.rule=Host(`courier.raketa.ru`) && PathPrefix(`/webhook/courier`)'
      - 'traefik.http.routers.courier.entrypoints=websecure'
      - 'traefik.http.routers.courier.tls=true'
      - 'traefik.http.routers.courier.tls.certresolver=le'
      - 'traefik.http.routers.courier.middlewares=strip-prefix'
      - 'traefik.http.services.courier.loadbalancer.server.port=80'

      # Admin bot
      - 'traefik.http.routers.admin.rule=Host(`admin.raketa.ru`) && PathPrefix(`/webhook/admin`)'
      - 'traefik.http.routers.admin.entrypoints=websecure'
      - 'traefik.http.routers.admin.tls=true'
      - 'traefik.http.routers.admin.tls.certresolver=le'
      - 'traefik.http.routers.admin.middlewares=strip-prefix'
      - 'traefik.http.services.admin.loadbalancer.server.port=80'

      # Partner bot
      - 'traefik.http.routers.partner.rule=Host(`partner.raketa.ru`) && PathPrefix(`/webhook/partner`)'
      - 'traefik.http.routers.partner.entrypoints=websecure'
      - 'traefik.http.routers.partner.tls=true'
      - 'traefik.http.routers.partner.tls.certresolver=le'
      - 'traefik.http.routers.partner.middlewares=strip-prefix'
      - 'traefik.http.services.partner.loadbalancer.server.port=80'

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false' # Рекомендуется для безопасности
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      # Настройки Let's Encrypt
      - '--certificatesresolvers.le.acme.email=${EMAIL}'
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.le.acme.httpchallenge=true'
      - '--certificatesresolvers.le.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - 'traefik_letsencrypt:/letsencrypt'
    networks:
      - raketa_network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./promtail-data:/data
    command: -config.file=/etc/promtail/config.yaml
    privileged: true
    networks:
      - raketa_network

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - raketa_network

networks:
  raketa_network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  redisdata:
  grafana_data:
  traefik_letsencrypt:
# services:
#   postgres:
#     image: postgres:14
#     container_name: postgres_raketa
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASS}
#     ports:
#       - '0.0.0.0:5432:5432'
#     networks:
#       - raketa_network
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: rabbitmq_raketa
#     restart: unless-stopped
#     environment:
#       RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
#       RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
#     ports:
#       - '127.0.0.1:5672:5672'
#       - '127.0.0.1:15672:15672'
#     networks:
#       - raketa_network
#     volumes:
#       - rabbitmq_data:/var/lib/rabbitmq

#   redis:
#     image: redis:7
#     container_name: redis_raketa
#     restart: unless-stopped
#     ports:
#       - '127.0.0.1:6379:6379'
#     command: ['redis-server', '--dir', '/data']
#     networks:
#       - raketa_network
#     volumes:
#       - redisdata:/data

#   grafana:
#     image: grafana/grafana:latest
#     container_name: grafana
#     restart: unless-stopped
#     ports:
#       - '3000:3000'
#     environment:
#       - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
#       - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
#       - GF_AUTH_ANONYMOUS_ENABLED=true
#       - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
#     networks:
#       - raketa_network
#     depends_on:
#       - postgres
#     volumes:
#       - grafana_data:/var/lib/grafana

#   raketa:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: raketa_bot
#     restart: unless-stopped
#     env_file:
#       - .env
#       - .env.local
#     depends_on:
#       - postgres
#       - rabbitmq
#       - redis
#     networks:
#       - raketa_network
#     ports:
#       - '127.0.0.1:8000:80'

#   promtail:
#     image: grafana/promtail:latest
#     container_name: promtail
#     restart: unless-stopped
#     ports:
#       - '9080:9080'
#     volumes:
#       - /var/lib/docker/containers:/var/lib/docker/containers:ro
#       - /var/run/docker.sock:/var/run/docker.sock:ro
#       - ./promtail-config.yaml:/etc/promtail/config.yaml
#       - ./promtail-data:/data # ← вот эта строка нужна
#     command: -config.file=/etc/promtail/config.yaml
#     privileged: true
#     networks:
#       - raketa_network
#   loki:
#     image: grafana/loki:latest
#     container_name: loki
#     restart: unless-stopped
#     ports:
#       - '3100:3100'
#     volumes:
#       - ./loki-config.yaml:/etc/loki/local-config.yaml
#     command: -config.file=/etc/loki/local-config.yaml
#     networks:
#       - raketa_network

# networks:
#   raketa_network:
#     driver: bridge

# volumes:
#   rabbitmq_data:
#   postgres_data:
#   redisdata:
#   grafana_data:
