services:
  postgres:
    image: postgres:14
    container_name: postgres_raketa
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - raketa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_raketa
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks:
      - raketa_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:7
    container_name: redis_raketa
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--dir', '/data']
    networks:
      - raketa_network
    volumes:
      - redisdata:/data
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - raketa_network
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  raketa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raketa_bot
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - raketa_network
    expose:
      - '80'
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.customer-stripprefix.stripprefix.prefixes=/customer'
      - 'traefik.http.middlewares.courier-stripprefix.stripprefix.prefixes=/courier'
      - 'traefik.http.middlewares.admin-stripprefix.stripprefix.prefixes=/admin'
      - 'traefik.http.middlewares.partner-stripprefix.stripprefix.prefixes=/partner'
      - 'traefik.http.services.raketa_bot.loadbalancer.server.port=80'
      - 'traefik.http.routers.customer.rule=Host(`customer.raketago.ru`) && PathPrefix(`/customer`)'
      - 'traefik.http.routers.customer.entrypoints=websecure'
      - 'traefik.http.routers.customer.tls=true'
      - 'traefik.http.routers.customer.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.customer.middlewares=customer-stripprefix'
      - 'traefik.http.routers.customer.service=raketa_bot'
      - 'traefik.http.routers.courier.rule=Host(`courier.raketago.ru`) && PathPrefix(`/courier`)'
      - 'traefik.http.routers.courier.entrypoints=websecure'
      - 'traefik.http.routers.courier.tls=true'
      - 'traefik.http.routers.courier.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.courier.middlewares=courier-stripprefix'
      - 'traefik.http.routers.courier.service=raketa_bot'
      - 'traefik.http.routers.admin.rule=Host(`admin.raketago.ru`) && PathPrefix(`/admin`)'
      - 'traefik.http.routers.admin.entrypoints=websecure'
      - 'traefik.http.routers.admin.tls=true'
      - 'traefik.http.routers.admin.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.admin.middlewares=admin-stripprefix'
      - 'traefik.http.routers.admin.service=raketa_bot'
      - 'traefik.http.routers.partner.rule=Host(`partner.raketago.ru`) && PathPrefix(`/partner`)'
      - 'traefik.http.routers.partner.entrypoints=websecure'
      - 'traefik.http.routers.partner.tls=true'
      - 'traefik.http.routers.partner.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.partner.middlewares=partner-stripprefix'
      - 'traefik.http.routers.partner.service=raketa_bot'

  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - '--api.dashboard=true'
      - '--log.level=INFO'
      - '--providers.docker=true'
      - '--providers.docker.exposedByDefault=false'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
      - '--entrypoints.web.http.redirections.entryPoint.scheme=https'
      - '--certificatesresolvers.letsencrypt.acme.email=r66cha@gmail.com'
      - '--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge=true'
      - '--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '443:443'
      - '127.0.0.1:8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - './letsencrypt:/letsencrypt'
    networks:
      - raketa_network
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - ./promtail-data:/tmp
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - raketa_network
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - raketa_network
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'

networks:
  raketa_network:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  redisdata:
  grafana_data:
  traefik_letsencrypt:
  loki-data:
  promtail-data:
