services:
  postgres:
    image: postgres:14
    container_name: postgres_raketa
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '0.0.0.0:5432:5432'
    networks:
      - raketa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_raketa
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks:
      - raketa_network

  redis:
    image: redis:7
    container_name: redis_raketa
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--dir', '/data']
    networks:
      - raketa_network
    volumes:
      - redisdata:/data

  raketa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raketa_bot
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - raketa_network
    ports:
      - '127.0.0.1:8000:80'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - raketa_network
    depends_on:
      - postgres
    volumes:
      - grafana_data:/var/lib/grafana

    loki:
      image: grafana/loki:2.9.1
      container_name: loki
      restart: unless-stopped
      ports:
        - '3100:3100'
      command: -config.file=/etc/loki/local-config.yaml
      networks:
        - raketa_network
      volumes:
        - ./loki-config.yaml:/etc/loki/local-config.yaml

    promtail:
      image: grafana/promtail:2.9.1
      container_name: promtail
      restart: unless-stopped
      networks:
        - raketa_network
      volumes:
        - ./promtail-config.yaml:/etc/promtail/config.yaml
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/log:/var/log
      command: -config.file=/etc/promtail/config.yaml

networks:
  raketa_network:
    driver: bridge

volumes:
  postgres_data:
  redisdata:
  grafana_data:
