version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_raketa
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - '127.0.0.1:5432:5432'
    networks:
      - raketa_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_raketa
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks:
      - raketa_network

  redis:
    image: redis:7
    container_name: redis_raketa
    restart: unless-stopped
    ports:
      - '127.0.0.1:6379:6379'
    command: ['redis-server', '--dir', '/data']
    networks:
      - raketa_network
    volumes:
      - redisdata:/data

  raketa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raketa_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - raketa_network
    ports:
      - '127.0.0.1:8000:80'

networks:
  raketa_network:
    driver: bridge

volumes:
  postgres_data:
  redisdata:
