server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  url: http://172.21.0.5:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa_bot_logs
          container: raketa_bot
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            log: log

      - regex:
          expression: 'level=(?P<level>\w+)\s+ts=(?P<ts>[^ ]+)\s+caller=(?P<caller>[^ ]+)\s+msg="(?P<msg>.*)"'

      - labels:
          level:
          caller:

      - output:
          source: msg
