server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # - job_name: 'raketa_logs'
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: raketa_bot
  #         service: raketa_bot
  #         __path__: /var/lib/docker/containers/*raketa_bot*/*.log
  #   pipeline_stages:
  #     - docker: {}

  - job_name: 'traefik_logs'
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik
          service: traefik
          __path__: /var/lib/docker/containers/*traefik*/*.log
    pipeline_stages:
      - docker: {}
