server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa_bot
          __path__: /var/lib/docker/containers/*raketa_bot*/*-json.log

    pipeline_stages:
      - json:
          expressions:
            log: log
      - regex:
          expression: '^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d+) - (?P<level>\w+): (?P<msg>.*)$'
      - timestamp:
          source: ts
          format: '2006-01-02 15:04:05,000'
      - labels:
          level:
      - output:
          source: msg
