scrape_configs:
  - job_name: raketa_bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa_bot
          __path__: /var/lib/docker/containers/*/*-json.log

    relabel_configs:
      - source_labels: [__meta_container_name]
        regex: raketa_bot
        action: keep

    pipeline_stages:
      - json:
          expressions:
            log: log
      - regex:
          expression: '^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d+) - (?P<level>\w+): (?P<msg>.*)$'
      - timestamp:
          source: ts
          format: '2006-01-02 15:04:05,000'
      - labels:
          level:
      - output:
          source: msg
