# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0
#   log_level: debug
# positions:
#   filename: /data/positions.yaml
# clients:
#   - url: http://loki:3100/loki/api/v1/push
# scrape_configs:
#   - job_name: docker_logs
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: docker_logs
#           service_name: docker_logs
#           __path__: /var/lib/docker/containers/*/*-json.log
#     pipeline_stages:
#       - docker: {}
#       - json:
#           expressions:
#             log: log
#             container_name: container_name
#       - labels:
#           container_name:
#       - output:
#           source: log
#       - drop:
#           source: structured_metadata
#           action: drop

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Фильтруем только raketa_bot по имени контейнера
      - source_labels: [__meta_docker_container_name]
        regex: /raketa_bot
        action: keep

      # Добавим service_name как отдельную метку
      - target_label: service_name
        replacement: raketa_bot

      # Путь к лог-файлу контейнера
      - source_labels: [__meta_docker_container_logfile]
        target_label: __path__

    pipeline_stages:
      - docker: {}
