server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: raketa_bot
        action: keep

      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log

      - target_label: job
        replacement: raketa_bot_logs

    pipeline_stages:
      - docker: {}

      - regex:
          expression: '^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}),\d+ - (?P<level>[A-Z]+): (?P<msg>.*)'

      - timestamp:
          source: ts
          format: '2006-01-02 15:04:05'
          location: Europe/Moscow # или UTC — в зависимости от твоей системы

      - labels:
          level:

      - output:
          source: msg
