scrape_configs:
  - job_name: raketa_bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa_bot_logs
          container: raketa_bot
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            ts: time
      - timestamp:
          source: ts
          # формат времени в Docker JSON: 2025-05-21T08:01:31.531Z
          format: RFC3339Nano
          # Здесь можно попробовать добавить смещение +3 часа, но в Promtail такого прямо нет
