server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: 'raketa_bot'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Оставляем только контейнер raketa_bot
      - source_labels: [__meta_docker_container_name]
        regex: /raketa_bot
        action: keep

      # Устанавливаем понятный label service_name
      - source_labels: [__meta_docker_container_name]
        regex: /?(.*)
        target_label: raketa
        replacement: $1

      # Эти тоже можно оставить для полноты
      - source_labels: [__meta_docker_container_name]
        regex: /?(.*)
        target_label: container
        replacement: $1

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

    pipeline_stages:
      - docker: {}
