server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          service_name: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log

    pipeline_stages:
      - docker: {}

      # Первый слой JSON — docker
      - json:
          expressions:
            log: log
            stream: stream
            time: time

      # Проверим: похоже ли содержимое log на JSON?
      - match:
          selector: '{job="docker_logs"}'
          stages:
            - regex:
                expression: '^\s*{.*}\s*$' # строка начинается с {
            - json:
                source: log
                # можешь указать expressions: {} если нужны конкретные поля

      - labels:
          container_name:
          level:
