server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 3s

scrape_configs:
  - job_name: raketa_bot_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: raketa_bot
        action: keep

      - target_label: service_name
        replacement: raketa_bot

      - source_labels: [__meta_docker_container_logfile]
        target_label: __path__

    pipeline_stages:
      - regex:
          expression: 'level=(?P<level>\w+)\s+ts=(?P<ts>[^ ]+)\s+caller=(?P<caller>[^ ]+)\s+component=(?P<component>[^ ]+)\s+msg="(?P<msg>[^"]+)"'
      - timestamp:
          source: ts
          format: RFC3339Nano
      - labels:
          level: ''
          caller: ''
          component: ''
