server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: http://172.21.0.5:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: raketa_bot
        action: keep

      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/$1-json.log

      - target_label: job
        replacement: raketa_bot_logs # ← гарантированный label для Loki

      - source_labels: [__meta_docker_container_name]
        target_label: container_name # ← дополнительный лейбл (опциональный)

    pipeline_stages:
      - docker: {}

      - labels:
          job:
          container_name:
