server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: debug

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      # Сначала отбрасываем promtail
      - source_labels: [__meta_docker_container_name]
        regex: promtail
        action: drop

      # Затем оставляем только raketa_bot
      - source_labels: [__meta_docker_container_name]
        regex: raketa_bot
        action: keep

      - target_label: job
        replacement: raketa_bot

    pipeline_stages: []
