# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0
#   log_level: debug
# positions:
#   filename: /data/positions.yaml
# clients:
#   - url: http://loki:3100/loki/api/v1/push
# scrape_configs:
#   - job_name: docker_logs
#     static_configs:
#       - targets:
#           - localhost
#         labels:
#           job: docker_logs
#           service_name: docker_logs
#           __path__: /var/lib/docker/containers/*/*-json.log
#     pipeline_stages:
#       - docker: {}
#       - json:
#           expressions:
#             log: log
#             container_name: container_name
#       - labels:
#           container_name:
#       - output:
#           source: log
#       - drop:
#           source: structured_metadata
#           action: drop

server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /data/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: raketa_bot_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa_logs
          service_name: raketa_bot
          __path__: /var/lib/docker/containers/*raketa_bot*/*-json.log

    pipeline_stages:
      - docker: {}
