# server:
#   http_listen_port: 9080
#   grpc_listen_port: 0
#   log_level: debug

# positions:
#   filename: /data/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: raketa_bot_logs
#     docker_sd_configs:
#       - host: unix:///var/run/docker.sock
#         refresh_interval: 5s

#     relabel_configs:
#       - source_labels: [__meta_docker_container_name]
#         regex: /promtail
#         action: drop
#       - source_labels: [__meta_docker_container_name]
#         regex: /raketa_bot
#         action: keep
#       - target_label: job
#         replacement: raketa_bot
#       - source_labels: [__meta_docker_container_name]
#         regex: /(.+)
#         target_label: container
#         replacement: $1

#     pipeline_stages:
#       - docker: {}
#       - output:
#           source: log

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: raketa
          __path__: /var/log/containers/*.log
    pipeline_stages:
      - docker: {}
      - output:
          source: log
